### ISSUE TITLE
How to use IOCTL_STORAGE_FIRMWARE_DOWNLOAD?

### ISSUE THREAD

**Issue by NextStory1127** [ken-yossy/nvmetool-win#15]
Update the Windows device through IOCTL_STORAGE_FIRMWARE_DOWNLOAD, the windows computer directly prompts the crash prompt "SYSTEM_SERVICE_EXCEPTION", How to use IOCTL_STORAGE_FIRMWARE_DOWNLOAD?

thanks

**Comment by ken-yossy** [comment]
Hi,

I think the usage of IOCTL_STORAGE_FIRMWARE_DOWNLOAD is well described in [this page](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/upgrading-firmware-for-an-nvme-device).
But I have not confirmed that the code really works... because updating firmware is highly dangerous (this is the reason that I do not implement it).

Regards,
Ken

**Comment by NextStory1127** [comment]
Thank you very much, successfully upgraded the firmware through IOCTL_SCSI_MINIPORT

**Comment by ken-yossy** [comment]
Great! I'm glad to hear that and it's my pleasure.

Regards,
Ken
