### ISSUE TITLE
Windows does not recognize PhysicalDrive%hs, how to send IOCTL commands to SSD?

### ISSUE THREAD

**Issue by NextStory1127** [ken-yossy/nvmetool-win#16]
Send a command to the SSD, open PhysicalDrive%hs through CreateFile, and then send the IOCTL command to the SSD. 
If Windows does not recognize PhysicalDrive%hs (for example, the SSD device does not start normally), is there a way to send an IOCTL command to the SSD? Similar to the character device that can send IOCTL to SSD under Linux 

Thanks

**Comment by ken-yossy** [comment]
Hi,

> If Windows does not recognize PhysicalDrive%hs (for example, the SSD device does not start normally), is there a way to send an IOCTL command to the SSD? Similar to the character device that can send IOCTL to SSD under Linux

I agree that the situation that you point out can happen, but I have no idea to do that...

All Microsoft's document that I found about DeviceIoControl()  (ex. https://docs.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-deviceiocontrol) depends on the file handles that can be retrieved by CreateFile().
And also, calling CreateFile() requires valid "FileName"...

I'm afraid that it could be done if we can make Windows recognize the device in such situation through doing device recognition process step by step (instead of Windows' auto-recognition)...

Thank you,
Ken

**Comment by NextStory1127** [comment]
I understand,  If  use the Microsoft Inbox,  need to ensure the normal operation of the device,  Because there is no Windows closed source driver, don't know Windows in the step by step device recognition process .

Thank you
