### ISSUE TITLE
Get Log Page option for raw-binary DATA

### ISSUE THREAD

**Issue by ankitsingh1508** [ken-yossy/nvmetool-win#23]
Hi,

Want to read DATA in raw-binary format but as per "PSTORAGE_PROTOCOL_SPECIFIC_DATA" i cant find the parameter to be set for this.
Can you please give me for the same?

**Comment by ken-yossy** [comment]
Hi !

> Want to read DATA in raw-binary format but as per "PSTORAGE_PROTOCOL_SPECIFIC_DATA" i cant find the parameter to be set for this. Can you please give me for the same?

You are correct, it does not have such a parameter and function that output the data of `struct _STORAGE_PROTOCOL_SPECIFIC_DATA` for commands in binary (raw) format.

I recommend that you implement such a function to this program by yourself (to cloned / copied source code), because you can completely customize the behavior as you like (or want).

In the following code (in `NVMeSMART.c` for example), variable `protocolData` points the data you want
```
    ZeroMemory(buffer, bufferLength);

    query = (PSTORAGE_PROPERTY_QUERY)buffer;
    protocolDataDescr = (PSTORAGE_PROTOCOL_DATA_DESCRIPTOR)buffer;
    protocolData = (PSTORAGE_PROTOCOL_SPECIFIC_DATA)query->AdditionalParameters;
```

I think it's not difficult for you!

Thank you!
Ken
