### ISSUE TITLE
no firmware download/commit

### ISSUE THREAD

**Issue by tim-oleksii** [ken-yossy/nvmetool-win#8]
I see that this application lacks FW processing routines. Is it possible to add them?

One trick - since Win10 2004 only CA=3 is supported.

**Comment by ken-yossy** [comment]
Hi Alexey,

Thank you for your comment.

As you mentioned, this tool does not support Firmware Update (image download and commit) feature defined in NVMe spec.
But it is intended because FW update is highly dangerous process and also drive (manufacture) dependent.
For the worst case, SSDs could turn into bricks...

So I am not going to add them at this time.

Regards,
Ken

**Comment by ken-yossy** [comment]
If there's no further comment, I would like to close this ticket a week later. 

Thank you,
Ken
